### ISSUE TITLE
Purpose of sink state

### ISSUE THREAD

**Issue by cipollone** [MarcoFavorito/rltg#41]
### Subject of the issue

The RewardDFA adds a sink state. Is this an intended behaviour? There will be formulae that may never fail. Also, if a sink state exists, that will be included in the automaton already.

If we want the ability to distinguish such a state, we could detect a sink by traversing the graph.
What do you think?

**Comment by marcofavorito** [comment]
the problem is that there might be some propositional interpretation with some proposition outside the alphabet of the automaton that does not trigger any existing transition. So we will always have a sink state. 

The above makes sense when talking about a closed-world assumption. An open-world assumption would make it work assuming that propositions that don't occur in the alphabet are considered as don't care, and so filter them out before computing the successors.

**Comment by marcofavorito** [comment]
So the issue could be reduced to decide whether to change the policy about unexpected fluents, filtering them out before evaluating successor states in the underlying state machine. Thoughts?

**Comment by marcofavorito** [comment]
Also, note the following. The class `RewardDFA` builds on top of the interface `DFA`, which unfortunately does not specify whether `get_successors` assumes the "closed-world" or the "open-world". The former in some sense cares about "safety", whereas the latter cares about "liveness".

`SymbolicDFA`, for instance, is "open", whereas `SimpleDFA` is closed, so it is also implementation-dependent. One may argue that `get_successors` is a case of [leaky abstraction](https://en.wikipedia.org/wiki/Leaky_abstraction)?

**Comment by cipollone** [comment]
Nice discussion.
So, in principle, I would prefer to have all alphabet explicits, so that we can immediately understand wether a fluent is missing because it's false or because our fluents evaluator doesn't evaluate it. This will prevent sneaky programming errors.

Do we have such alphabet in SymbolicDFA? If we don't, is it intentional?
Another problem is that right now a fluent extractor is:
`FluentExtractor = Callable[[Observation, Optional[Action]], Interpretation]`
Instead, I would define it as an abstract class so that we can retrieve its alphabet and check inside `RewardDFA`.

What do you think, instead?

**Comment by marcofavorito** [comment]
- No we don't have explicit checks on the alphabet. Probably we should, although I guess it is a trade-off between consistency and easy of use; any addition of a new fluent would imply a change to every reward DFA.
- Instead of `FluentExtractor` being an abstract class, it could be left as a type hint, and if you want a check on the alphabet, you can provide a callable object instead, maybe implementing an abstract base class, and delegate any custom (specialized) behaviour to the client code.

**Comment by marcofavorito** [comment]
Removed in #120, thank you @cipollone .
